{
  sequence: findSequence(argorgname:"yeast",argrefseq:"chrI", argfmin: 0, argflen: 100) 
}



{
  findFeatures(organismName:"yeast",refseq:"chrI", sotype:"gene", fmin:1, fmax:1000) {
    edges {
      node {
        name
        dbxrefId
        uniquename
        cvtermByTypeId {
          name
        }
        isAnalysis
        isObsolete
        featurelocsByFeatureId {
          nodes {
            fmax
            fmin
            strand
            isFminPartial
            isFmaxPartial
          }
        }
        featureRelationshipsByObjectId {
          edges {
            node {
              featureBySubjectId {
                name
                dbxrefId
                uniquename
                cvtermByTypeId {
                  name
                }
                isAnalysis
                isObsolete
                featurelocsByFeatureId {
                  nodes {
                    fmax
                    fmin
                    strand
                    isFminPartial
                    isFmaxPartial
                  }
                }
                featureRelationshipsByObjectId {
                  edges {
                    node {
                      featureBySubjectId {
                        name
                        dbxrefId
                        uniquename
                        cvtermByTypeId {
                          name
                        }
                        isAnalysis
                        isObsolete
                        featurelocsByFeatureId {
                          nodes {
                            fmax
                            fmin
                            strand
                            isFminPartial
                            isFmaxPartial
                          }
                        }
                        featureRelationshipsByObjectId {
                          edges {
                            node {
                              featureBySubjectId {
                                name
                                dbxrefId
                                uniquename
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
